// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexTokenUsage } from "./CodexTokenUsage";

export type CodexTokenUsageInfo = { total_token_usage: CodexTokenUsage, last_token_usage: CodexTokenUsage, model_context_window: number | null, };
