// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexUsageWindow } from "./CodexUsageWindow";

export type CodexUsageRateLimits = { primary: CodexUsageWindow | null, secondary: CodexUsageWindow | null, };
