// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodexUsageWindow = { used_percent: number, window_minutes: number | null, resets_in_seconds: number | null, };
