// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexTokenUsageInfo } from "./CodexTokenUsageInfo";
import type { CodexUsageRateLimits } from "./CodexUsageRateLimits";

export type CodexUsageSnapshot = { captured_at: string, rate_limits: CodexUsageRateLimits, token_usage: CodexTokenUsageInfo | null, };
